apiVersion: v1
kind: Service
metadata:
  name: assignment2
spec:
  selector:
    app: assignment2
  ports:
    - port: 30000
      targetPort: 30000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: assignment2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assignment2
  template:
    metadata:
      labels:
        app: assignment2
    spec:
      containers:
        - name: app
          image: edwardlecoding/comp4016-assignment2:latest
          ports:
            - containerPort: 30000
          env:
            - name: envValue
              value: environmentSnake
          imagePullPolicy: Always
