apiVersion: v1
kind: Namespace
metadata:
  name: edwardlecoding
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: assignment2config
  namespace: edwardlecoding
data:
  configValue: snake

---
apiVersion: v1
kind: Service
metadata:
  name: assignment2
  namespace: edwardlecoding
spec:
  type: NodePort
  selector:
    app: assignment2
  ports:
    - port: 30000
      targetPort: 30000
      nodePort: 30000
---
apiVersion: v1
kind: Secret
metadata:
  name: assignment2secret
  namespace: edwardlecoding
data:
  secretValue: c2VjcmV0U25ha2U=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: assignment2
  namespace: edwardlecoding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assignment2
  template:
    metadata:
      labels:
        app: assignment2
    spec:
      containers:
        - name: app
          image: edwardlecoding/comp4016-assignment2:latest
          ports:
            - containerPort: 30000
          env:
            - name: envValue
              value: environmentSnake
            - name: SECRET_VALUE
              valueFrom:
                secretKeyRef:
                  name: assignment2secret
                  key: secretValue
            - name: CONFIG_VALUE
              valueFrom:
                configMapKeyRef:
                  name: assignment2config
                  key: configValue
          imagePullPolicy: Always
          volumeMounts:
            - name: config
              mountPath: "/config/.env"
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: assignment2config
